### ISSUE TITLE
无法下载参考文献PDF

### ISSUE THREAD

**Issue by guannaiyang** [HCPLab-SYSU/Book-of-MLM#1]
Hi，刘教授：

感谢您的大作！让我学习很多！我想下载参考文献PDF，以查找一些文献，确认一些技术细节。但是，好像下载不了，可否发我邮箱：nyguan@sina.com。谢谢！

乃洋

**Comment by YangLiu9208** [comment]
感谢您的关注，参考文献下载地址是https://raw.githubusercontent.com/HCPLab-SYSU/Book-of-MLM/main/Resources/Reference.pdf 。

**Comment by HCPLab-SYSU** [comment]
感谢您的关注，参考文献下载地址是https://raw.githubusercontent.com/HCPLab-SYSU/Book-of-MLM/main/Resources/Reference.pdf 。
