### ISSUE TITLE
已在京东买了书，同步想问下其他的PPT教材什么时候可以更新呢？

### ISSUE THREAD

**Issue by zxbloved** [HCPLab-SYSU/Book-of-MLM#2]

**Comment by HCPLab-SYSU** [comment]
您好，PPT目前正在整理中，预计6月左右会更新完毕。

**Comment by zxbloved** [comment]
假期认真看了下书，整理来说对于理论知识和专业知识覆盖的比较全。但是对于我们这种从普通程序员入门去做人工智能这块，对于算法的部分，看的确实会比较吃力。希望能出一些视频讲解，结合来学习。这样会更好的理解，谢谢。

**Comment by HCPLab-SYSU** [comment]
非常感谢您的建议，视频讲解这个提议非常好，我们会考虑您的建议，逐渐完善的！
