### ISSUE TITLE
PPT的图片非常模糊，看不清

### ISSUE THREAD

**Issue by CaiJichang212** [HCPLab-SYSU/Book-of-MLM#4]
![image](https://github.com/user-attachments/assets/32c79e43-c671-4645-b5f9-ae5123728ed8)
非常感谢你们能分享PPT文件。
PPT的图片非常模糊，看不清，特别是这里T的下标，请问能给出这些图片的出处吗？非常感谢。

**Comment by HCPLab-SYSU** [comment]
抱歉给您带来不便，可能是ppt保存图片自动降低了分辨率，我们尽快更新一下课件的图片，这张图是书的P127,图3.4。
