### ISSUE TITLE
写得太匆忙

### ISSUE THREAD

**Issue by imwei25** [HCPLab-SYSU/Book-of-MLM#5]
看了两三章。个人怀疑文章有相当一部分ai写的或者ai翻译的内容，因为句子读的都不通顺，甚至有些内容也缺失，比如有标题写着弱监督学习，底下内容却连个定义都没有，还有引用文献只有个数字，还要自己来找，观感很差。

**Comment by HCPLab-SYSU** [comment]
参考文献由于版面限制没有印刷出来，只能以线上电子版形式公开，还请您理解。
